ALL_VAR = 'all'
ORDER_VAR = 'o'
ORDER_TYPE_VAR = 'ot'
PAGE_VAR = 'p'
SEARCH_VAR = 'q'

SAVE_CONTINUE_VAR = '_continue'
SAVE_ADD_ANOTHER_VAR = '_saveaddanother'
SAVE_AS_NEW_VAR = '_saveasnew'

IGNORED_PARAMS = (
    ALL_VAR, ORDER_VAR, ORDER_TYPE_VAR, SEARCH_VAR, IS_POPUP_VAR, TO_FIELD_VAR
)
