# Generated by Django 2.0.6 on 2018-07-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Inputter',
        ),
    ]
